autoerp/autoerp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
]

from django.conf import settings

if 'contact' in settings.INSTALLED_APPS:
    urlpatterns.append(url(r'^contact/', include('contact.urls', namespace='contact')))

autoerp/contact/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
            url(r'^$', views.index, name='index'),
            url(r'^(?P<page>[0-9]+)/$', views.index, name='index'),
            url(r'^(?P<page>[0-9]+)/(?P<itemsByPage>[0-9]+)/$', views.index, name='index'),
            url(r'^people/$', views.people_index, name='people_index'),
            url(r'^company/$', views.company_index, name='company_index'),
            url(r'^company/(?P<item_id>[0-9]+)/$', views.company_view, name='company_view'),
                ]

autoerp/main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
            # ex: /polls/
            url(r'^$', views.index, name='index'),
            url(r'^login/$', views.user_login, name='login'),
            url(r'^logout/$', views.user_logout, name='logout'),
            #url(r'^accounts/login/', views.index, name='login'),
            # ex: /polls/5/
            #url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
            # ex: /polls/5/results/
            #url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
            # ex: /polls/5/vote/
            #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
                ]

autoerp/contact/models.py
from django.db import models
from polymorphic.models import PolymorphicModel

# Create your models here.


class Contact(PolymorphicModel):
    name = models.CharField(max_length=254)
    address_1 = models.CharField(max_length=254, blank=True)
    address_2 = models.CharField(max_length=254, blank=True)
    zipcode = models.CharField(max_length=254, blank=True)
    city = models.CharField(max_length=254, blank=True)
    telephone = models.CharField(max_length=254, blank=True)
    telephone_mobile = models.CharField(max_length=254, blank=True)
    telephone_pro = models.CharField(max_length=25, blank=True)
    fax = models.CharField(max_length=254, blank=True)
    email = models.EmailField(blank=True)
    website = models.URLField(blank=True)
    note = models.TextField(blank=True)


class People(Contact):
    first_name = models.CharField(max_length=254, blank=True)

    def __str__(self):
        return (self.first_name+' '+self.name)

    def isPeople(self):
        return True


class Company(Contact):
    siret = models.PositiveIntegerField()
    raison_sociale = models.CharField(max_length=254)
    peoples = models.ManyToManyField(People, through='Job')

    def __str__(self):
        return self.name

    def isCompany(self):
        return True



class Job(models.Model):
    peoples = models.ForeignKey(People, on_delete=models.CASCADE)
    companies = models.ForeignKey(Company, on_delete=models.CASCADE)
    situation = models.CharField(max_length=254, blank=True)
    
    def __str__(self):
        #if self.situation: intitule = self.contact+', '+self.situation+' chez '+self.company
        #else: intitule = self.contact+' chez '+self.company

        if self.situation: intitule = str(self.peoples)+', '+str(self.situation)+' chez '+str(self.companies)
        else: intitule = str(self.peoples)+' chez '+str(self.companies)
        return intitule

autoerp/main/models.py
from django.db import models

# Create your models here.

autoerp/contact/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Contact, People, Company, Job
from main.views import pagerDict

# Create your views here.



@login_required
def index(request,page=1,itemsByPage=5):
    firstItem = (int(page) - 1) * int(itemsByPage)
    print('firstItem : '+str(firstItem)) # DEBUG
    lastItem = int(firstItem + int(itemsByPage))
    print('lastItem : '+str(lastItem)) # DEBUG
    contacts = Contact.objects.all()[firstItem:lastItem]
    context = {
            'contacts' : contacts, 
            'pager':     pagerDict(Contact, page, itemsByPage, 'contact:index'),   
            }
    return render(request, 'contact/index.html', context)


@login_required
def company_index(request):
    contacts = Company.objects.all()

    return render(request, 'contact/index.html', {'contacts' : contacts, })


@login_required
def company_view(request, item_id):
    #contacts = Company.objects.get(id=company_id)
    contact = get_object_or_404(Company, id=item_id)

    return render(request, 'contact/view.html', {'contact' : contact, })


@login_required
def company_edit(request, company_id):
    #contacts = Company.objects.get(id=company_id)
    contact = get_object_or_404(Company, id=company_id)

    return render(request, 'contact/company_form.html', {'company' : company, })


@login_required
def people_index(request):
    contacts = People.objects.all()

    return render(request, 'contact/index.html', {'contacts' : contacts, })


@login_required
def people_view(request, people_id):
    people = People.objects.get(id=people_id)

    return render(request, 'contact/index.html', {'people' : people, })

autoerp/main/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout, user_logged_in, login
from django.http import HttpResponseRedirect, HttpResponse

# Create your views here.

def pagerDict(itemClass, page, itemsByPage, pagerUrl):
    itemList = []
    for i in itemClass.objects.all():
        itemList.append(i.id)

    lastPage = int((len(itemList) -1) / int(itemsByPage)) +1
    print(len(itemList))
    

    pageList = []
    pageListWidth = 7
    for i in range(0,pageListWidth):
        n = int(page) - int(pageListWidth / 2) + i
        if n > 0 and n <= lastPage:
            pageList.append(n)

    pager = {
            'position':     page,  
            'lastPage':     lastPage,
            'itemsByPage':  itemsByPage,
            'itemClass':    itemClass,
            'pageList':     pageList,
            'pagerUrl':     pagerUrl
            }
    return pager


def user_login(request):
    context = RequestContext(request)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                #user_logged_in()
                #return render(request, 'main/index.html', {})
                return HttpResponseRedirect('/')
            else:
                #return render(request, 'autoerp/login.html', {})
                return HttpResponse("Votre compte est désactivé.")
        else:
            print("Invalid login details: {0}, {1}".format(username, password))
            #return render(request, 'autoerp/login.html', {})
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'autoerp/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return render(request, 'autoerp/login.html', {})



@login_required
def index(request):
    return render(request, 'main/index.html', {})

autoerp/contact/templates/contact/entreprise_modal.html
{% comment %}
{% endcomment %}

<div class="container">
	<button type="button" class="btn btn-default btn-md list-group-item" data-toggle="modal" data-target="#myModal{{ contact.id }}">
		<span class="glyphicon glyphicon-briefcase"></span> {{ contact }}</button>

		<div class="modal fade" id="myModal{{ contact.id }}" role="dialog">
			<div class="modal-dialog modal-lg">

				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title">
							{{ contact }}{% if contact.raison_sociale %} - {{ contact.raison_sociale }}{% endif %}</a>
							
						</h4>
					</div>
					<div class="modal-body">
						<div class="container-fluid">
							<div class="col-md-8">
								{% if contact.siret %}<strong>N° SIRET: </strong>{{ contact.siret }}<br><br>{% endif %}
									{% if contact.address_1 or contact.address_2 or contact.zipcode or contact.city %}
										{% if contact.address_1 %}{{ contact.address_1 }}<br>{% endif %}
										{% if contact.address_2 %}{{ contact.address_2 }}<br>{% endif %}
										{% if contact.zipcode %}{{ contact.zipcode }}<br>{% endif %}
										{% if contact.city %}{{ contact.city }}<br>{% endif %}
										<br>
									{% endif %}

									{% if contact.telephone or contact.telephone_pro or contact.telephone_mobile %}
										{% if contact.telephone %}<strong>Téléphone: </strong>{{ contact.telephone }}<br>{% endif %}
										{% if contact.telephone_pro %}<strong>Téléphone professionnel: </strong>{{ contact.telephone_pro }}<br>{% endif %}
										{% if contact.telephone_mobile %}<strong>Téléphone mobile: </strong>{{ contact.telephone_mobile }}<br>{% endif %}
										{% if contact.fax %}<strong>Fax: </strong>{{ contact.fax }}<br>{% endif %}
										<br>
									{% endif %}

									{% if contact.email or contact.website %}
										{% if contact.email %}<strong>Email: </strong>{{ contact.email }}<br>{% endif %}
										{% if contact.website %}<strong>Site web: </strong>{{ contact.website }}<br>{% endif %}
										<br>
									{% endif %}
								
							</div>
							<div class="col-md-4">
								<ul>
								{% for job in contact.job_set.all %}
								<li><a href="#"><span class="glyphicon glyphicon-user"></span> {{ job.peoples }}</a><br><small>{{ job.situation }}</small></li>
								{% endfor %}
								</ul>
							</div>
							<div class="container">
								{{ contact.note }}
							</div>

						</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-edit"></span></button>
					<button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-trash"></span></button>
				</div>
			</div>

		</div>
	</div>

</div>

autoerp/contact/templates/contact/index.html
{% extends 'autoerp/base.html' %}
{% comment %}
	{% load app_filters %}
{% endcomment %}

{% block subnavbar %}
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="{% url 'contact:index'  %}">Contacts</a>
		</div>
		<ul class="nav navbar-nav">
			<li><a href="{% url 'contact:people_index'  %}">Personnes</a></li>
			<li><a href="{% url 'contact:company_index'  %}">Entreprises</a></li>
		</ul>
	</div>
</nav>
{% endblock %}


{% block content %}
<div class="container">
	<div class="list-group">
		{% for contact in contacts %}
			{% if contact.isPeople %}
				{% include "contact/personne_modal.html" %}
			{% elif contact.isCompany %}
				{% include "contact/entreprise_modal.html" %}
			{% endif %}
		{% endfor %}
	</div>	
	{% include "autoerp/pager.html" %}
</div>
{% endblock %}

autoerp/contact/templates/contact/personne_modal.html
{% comment %}
{% endcomment %}

<div class="container">
	<button type="button" class="btn btn-default btn-md list-group-item" data-toggle="modal" data-target="#myModal{{ contact.id }}">
		<span class="glyphicon glyphicon-user"></span> {{ contact }}</button>

		<div class="modal fade" id="myModal{{ contact.id }}" role="dialog">
			<div class="modal-dialog modal-lg">

				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title">
							{{ contact }}{% for job in contact.job_set.all %}, {{ job.situation }}	chez <a href="#"><span class="glyphicon glyphicon-briefcase"></span>{{ job.companies }}</a>
						{% endfor %}</h4>
					</div>
					<div class="modal-body">
						<div class="container-fluid">
							<div class="container">
									{% if contact.address_1 or contact.address_2 or contact.zipcode or contact.city %}
										{% if contact.address_1 %}{{ contact.address_1 }}<br>{% endif %}
										{% if contact.address_2 %}{{ contact.address_2 }}<br>{% endif %}
										{% if contact.zipcode %}{{ contact.zipcode }}<br>{% endif %}
										{% if contact.city %}{{ contact.city }}<br>{% endif %}
										<br>
									{% endif %}

									{% if contact.telephone or contact.telephone_pro or contact.telephone_mobile %}
										{% if contact.telephone %}<strong>Téléphone: </strong>{{ contact.telephone }}<br>{% endif %}
										{% if contact.telephone_pro %}<strong>Téléphone professionnel: </strong>{{ contact.telephone_pro }}<br>{% endif %}
										{% if contact.telephone_mobile %}<strong>Téléphone mobile: </strong>{{ contact.telephone_mobile }}<br>{% endif %}
										{% if contact.fax %}<strong>Fax: </strong>{{ contact.fax }}<br>{% endif %}
										<br>
									{% endif %}

									{% if contact.email or contact.website %}
										{% if contact.email %}<strong>Email: </strong>{{ contact.email }}<br>{% endif %}
										{% if contact.website %}<strong>Site web: </strong>{{ contact.website }}<br>{% endif %}
										<br>
									{% endif %}
							</div>
							<div class="container">
								{{ contact.note }}
							</div>

						</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-edit"></span></button>
					<button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-trash"></span></button>
				</div>
			</div>

		</div>
	</div>

</div>

autoerp/contact/templates/contact/view_item.html
{% extends "contact/index.html" %}

{% block content %}

<<h1>View de {{ contact }}</h1>>
	
{% endblock content %}

autoerp/main/templates/main/index.html
{% extends "autoerp/base.html" %}

{% block content %}
<h1>MAIN.INDEX</h1>
{% endblock %}

autoerp/templates/autoerp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<link rel="stylesheet" href="{% static "css/bootstrap.css" %}" />
		<link rel="stylesheet" href="{% static "css/starter-template.css" %}" />
		<script src="{% static "js/jquery.min.js" %}"></script>
		<script src="{% static "js/bootstrap.js" %}"></script>

		<title>AutoERP</title>
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'index' %}">AutoERP</a>
				</div>
				<div id="navbar" class="collapse navbar-collapse">
			{% block navbar %}
					<ul class="nav navbar-nav">
						{% if 'contact' in apps %}	<li><a href="{% url 'contact:index' %}">Contact</a></li>{% endif %}
						<li>
							<a href="{% url 'logout' %}" class="btn btn-inverse btn-lg">
								<span class="glyphicon glyphicon-off"></span>
							</a>
						</li>
					</ul>
			{% endblock %}
				</div><!--/.nav-collapse -->
			</div>
		</nav>

			{% block subnavbar %}
			{% endblock %}

		<div class="container">
			{% block content %}
			<h1>Welcome to AutoERP</h1>
			{% endblock %}
		</div>
	</body>
</html>

autoerp/templates/autoerp/login.html
{% extends "autoerp/base.html" %}
{% block navbar %}
{% endblock %}

{% block content %}
<div class="container">
	<div class="jumbotron">
		<h1>AutoERP - Connectez vous !</h1>
	</div>

<form id="login_form" method="post" action="/login/">
{% csrf_token %}
	<div class="form-group">
		<label for="login">Identifiant:</label>
		<input type="login" class="form-control" id="login" type="text" name="username">
	</div>
	<div class="form-group">
		<label for="password">Identifiant:</label>
		<input type="password" class="form-control" id="password" type="password" name="password">
	</div>
	<button type="submit" class="btn btn-default">Connexion</button>
</div>
{% endblock %}

autoerp/templates/autoerp/pager.html
{% comment %}
{% endcomment %}
<div class="col-sm-8">
<ul class="pagination pagination-sm">
	<li class="previous"><a href="{% url pager.pagerUrl  page='1' itemsByPage=pager.itemsByPage %}"><span class="glyphicon glyphicon-fast-backward"></span></a></li>
	{# <li class="previous"><a href="{% url pager.pagerUrl  page=page itemsByPage=pager.itemsByPage %}"><span class="glyphicon glyphicon-backward"></span></a></li>A #}

	{% for page in pager.pageList %}
		<li><a href="{% url pager.pagerUrl page pager.itemsByPage %}">{{ page }}</a></li>
	{% endfor %}

	{# <li class="next"><a href="{% url pager.pagerUrl page=pager.pageList.4 itemsByPage=pager.itemsByPage %}"><span class="glyphicon glyphicon-forward"></span></a></li> #}
	<li class="next"><a href="{% url pager.pagerUrl page=pager.lastPage itemsByPage=pager.itemsByPage %}"><span class="glyphicon glyphicon-fast-forward"></span></a></li>

</div>
<div class="col-sm-4">
	items par page:
</div>
</ul>